# https://taskfile.dev

version: "3"
env:
  BINARY_NAME: cockpitserver

tasks:
  dev_go:
    dir: .
    cmds:
      - go run -ldflags="-X 'main.BuildENV=development'" main.go

  build:
    dir: .
    cmds:
      - pkger
      - task: build_web
      - go build -o ./bin/${BINARY_NAME}.exe -ldflags="-X 'main.BuildENV=production'" main.go
      - cp SimConnect.dll bin/SimConnect.dll
  dev_web:
    dir: web
    cmds:
      - yarn dev

  build_web:
    dir: web
    cmds:
      - yarn build
    sources:
      - web/src/**/*
    method: timestamp

  run:
    dir: bin
    cmds:
      - ${BINARY_NAME}.exe
