# https://taskfile.dev

version: "3"
env:
  BINARY_NAME: cockpitserver

tasks:
  dev:
    dir: .
    cmds:
      - go run -ldflags="-X 'main.BuildENV=development'" main.go
    sources:
      - ./**/*.go
    method: timestamp
  build:
    dir: .
    cmds:
      - pkger
      - go build -o ./bin/${BINARY_NAME}.exe -ldflags="-X 'main.BuildENV=production'" main.go
  run:
    dir: bin
    cmds:
      - ${BINARY_NAME}.exe
